version: '3.8'

services:
  web:
    build: ./backend/TunisianBootee.Api
    ports:
      - "5000:80"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tunisian_bootee
    ports:
      - "5432:5432"
